swipe:
  3: 
    left: 
      command: 'xdotool key alt+Right'
    right: 
      command: 'xdotool key alt+Left'
    up: 
      command: 'xdotool key alt+Tab'
    down:
      command: 'xdotool key ctrl+Tab'
threshold:
  swipe: 0.4
interval:
  swipe: 0.8
